[package]
name = "examples"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dev-dependencies]
aeth.workspace = true
anyhow.workspace = true
winit.workspace = true

[[example]]
name = "blank"
path = "blank.rs"